In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

# **Checking contigiousness of array and taking transpose of array**

In [ ]:
arr = np.zeros((10,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
print(arr.flags['C_CONTIGUOUS'])
print(arr.flags['F_CONTIGUOUS'])

True
False


In [ ]:
Tarr = arr.T

In [ ]:
print(Tarr.flags['C_CONTIGUOUS'])
print(Tarr.flags['F_CONTIGUOUS'])


False
True


# Reshape numpy array

In [ ]:
arr2 = np.arange(10)
print(arr2)
# print(np.array(arr2))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_reshaped = np.reshape(arr2, (2,2))
print(arr_reshaped)

ValueError: ignored

# Difference of lists

In [ ]:
l1 = set(["google", "Facebook", "Microsoft"])
l2 = set(["Microsoft"])

l3 = l1.difference(l2)

print(l3)

{'google', 'Facebook'}


# **Finding R squred and Adjusted R squared**

In [2]:
from pandas import DataFrame
import statsmodels.api as sm
# making the fake dataset
data = { 
         'month': [12,11,10,9,8,7,6,5,4],
         'free_time': [120,110,100,90,80,85,60,50,40],
         'num_articles': [8,8,7,6,6,7,6,4,5]
       }
df = DataFrame(data, columns=['month', 'free_time', 'num_articles'])
# features
X = df[['free_time']] 
# target variable
Y = df['num_articles']
# adding a constant
X = sm.add_constant(X)
# applying method of least squares
model = sm.OLS(Y, X).fit()
predictions = model.predict(X)
print_model = model.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:           num_articles   R-squared:                       0.818
Model:                            OLS   Adj. R-squared:                  0.792
Method:                 Least Squares   F-statistic:                     31.55
Date:                Sat, 31 Dec 2022   Prob (F-statistic):           0.000802
Time:                        22:42:01   Log-Likelihood:                -7.0819
No. Observations:                   9   AIC:                             18.16
Df Residuals:                       7   BIC:                             18.56
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.7345      0.672      4.072      0.0

/usr/local/lib/python3.8/dist-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)
/usr/local/lib/python3.8/dist-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [13]:
import numpy
actual = [1,2,3,4,5]
predict = [1,2.5,3,4.9,4.9]
 
corr_matrix = numpy.corrcoef(actual, predict)
corr = corr_matrix[0,1]
R_sq = corr**2
 
print(R_sq)

0.934602946460654
