In [25]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd 

In [26]:
dataset = pd.read_csv('Data.csv')
X= dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [27]:
print(X)
print(type(X))

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
<class 'numpy.ndarray'>


In [28]:
print(type(X))
print(X)

<class 'numpy.ndarray'>
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [29]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# **Taking care of Missing data:**

In [30]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan , strategy = "mean")
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# **Encoding categorical data**

### OneHotEncoding

we have 3 categories (France, Spain, Germany) in our dataset, we cannot apply Simple Encoding by assigning the France 1, Spain 2, Germany 3. Because machine learning model will think that Germany is greater than the France beacuse Germany has a greater value then France. Since All these three categorical values doesnot have any corelation between them so we need to encode it in a way in which machine learning model will not give weight more to any of one catergorical value. 
So, we have one hot encoding technique in which encoder create seperate columns for all the unique values in categorical data colum (in our case it is 3). and assign each value 0 or 1 in the respective columns. like if we have the row of France, then the vector of that row would be [1 , 0 , 0] representing that, France is 1, Spain and Germany is 0. 


Params: remainder = "passthrough" will make sure that the remaining columns of the dataset will remain in the dataset during the fit_transform, otherwise, ColumnTransformer class will apply the transformation on the given column and remove all other columns. 

if we donot apply np.array() method in below code, then ColumnTranformer object will already give us the numpy array, so we donot need to apply np.array(). but in the course, instructor was apply so i am applying it too

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(), [0])], remainder = 'passthrough')
print(ct)

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [0])])


In [32]:
xok = ct.fit_transform(X)
print(xok)
print(type(xok))

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
<class 'numpy.ndarray'>


In [33]:
X = np.array(ct.fit_transform(X))
print(X)
print(type(X))

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
<class 'numpy.ndarray'>


### Label Encoding on Dependent column "Purchased"

We are applying labelencoder here, because there are only 2 values, yes or no in our dependent column. if we have more then 2 values, then we will apply one hot encoding

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


# **Train Test Split**

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2 , random_state = 1)

In [40]:
print(X_train)


[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [41]:
print(X_test)
print(y_train)
print(y_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


# **Feature Scaling**

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [49]:
print(X_train)
print(type(X_train))
print("Maximum Value: ",np.amax(X_train))
print("Minimum Value: ", np.amin(X_train))

[[-0.77459667 -0.57735027  1.29099445 -0.19159184 -1.07812594]
 [-0.77459667  1.73205081 -0.77459667 -0.01411729 -0.07013168]
 [ 1.29099445 -0.57735027 -0.77459667  0.56670851  0.63356243]
 [-0.77459667 -0.57735027  1.29099445 -0.30453019 -0.30786617]
 [-0.77459667 -0.57735027  1.29099445 -1.90180114 -1.42046362]
 [ 1.29099445 -0.57735027 -0.77459667  1.14753431  1.23265336]
 [-0.77459667  1.73205081 -0.77459667  1.43794721  1.57499104]
 [ 1.29099445 -0.57735027 -0.77459667 -0.74014954 -0.56461943]]
<class 'numpy.ndarray'>
Maximum Value:  1.7320508075688774
Minimum Value:  -1.9018011447007988
